src/Entity/Book.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Book
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $owner;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $location;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $location_updated_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_borrowed;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="books")
     */
    private $current_reader;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getOwner(): ?string
    {
        return $this->owner;
    }

    public function setOwner(string $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getLocationUpdatedAt(): ?\DateTimeInterface
    {
        return $this->location_updated_at;
    }

    public function setLocationUpdatedAt(\DateTimeInterface $location_updated_at): self
    {
        $this->location_updated_at = $location_updated_at;

        return $this;
    }

    public function getIsBorrowed(): ?bool
    {
        return $this->is_borrowed;
    }

    public function setIsBorrowed(bool $is_borrowed): self
    {
        $this->is_borrowed = $is_borrowed;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCurrentReader(): ?User
    {
        return $this->current_reader;
    }

    public function setCurrentReader(?User $current_reader): self
    {
        $this->current_reader = $current_reader;

        return $this;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function updateTimestamps()
    {
        $this->setUpdatedAt(new \DateTime('now'));
        $this->setLocationUpdatedAt(new \DateTime('now'));

        if ($this->getCreatedAt() == null) {
            $this->setCreatedAt(new \DateTime('now'));
        }
    }

    /**
     * @ORM\PrePersist
     */
    public function setInitialIsBorrowed()
    {
        $this->setIsBorrowed(false);
    }
}

src/Form/BookType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('author')
            ->add('owner')
            ->add('location')
            ->add('description', TextareaType::class)
            ->add('save', SubmitType::class);
    }

}

src/Controller/BooksController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Form\BookLocationType;
use App\Form\BookType;
use App\Repository\BookRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/books")
 */
class BooksController extends AbstractController
{
    /**
     * @Route("/")
     */
    public function list() {
        $books = $this->getDoctrine()->getRepository(Book::class)->findAll();

        return $this->render('books/list.html.twig', [
            'books' => $books
        ]);
    }

    /**
     * @Route("/add")
     */
    public function add(Request $request)
    {
        $book = new Book();
        $form = $this->createForm(BookType::class, $book);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($book);
            $entityManager->flush();

            return $this->redirectToRoute('app_books_list');
        }

        return $this->render('books/add.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{id<\d+>}")
     */
    public function show($id)
    {
        $book = $this->getDoctrine()->getManager()->getRepository(Book::class)->find($id);

        return $this->render('books/show.html.twig', [
            'book' => $book
        ]);
    }

    /**
     * @Route("/edit/{id<\d+>}")
     */
    public function edit(Request $request, $id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $book = $entityManager->getRepository(Book::class)->find($id);
        $form = $this->createForm(BookType::class, $book);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_books_list');
        }

        return $this->render('books/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/borrow/{id<\d+>}")
     */
    public function borrow($id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $book = $entityManager->getRepository(Book::class)->find($id);
        $book->setIsBorrowed(true);
        $book->setCurrentReader($this->getUser());
        $entityManager->flush();

        return $this->render('books/borrow_success.html.twig');
    }

    /**
     * @Route("/return/{id<\d+>}")
     */
    public function return($id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $book = $entityManager->getRepository(Book::class)->find($id);
        $book->setIsBorrowed(false);
        $book->setCurrentReader(null);
        $entityManager->flush();

        return $this->render('books/return_success.html.twig');
    }

    /**
     * @Route("/update-location/{id<\d+>}", name="app_books_update_location")
     */
    public function updateLocation(Request $request, $id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $book = $entityManager->getRepository(Book::class)->find($id);
        $form = $this->createForm(BookLocationType::class, $book, [
            'action' => $this->generateUrl('app_books_update_location', ['id' => $id])
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            $referer = $request->headers->get('referer');

            if ($referer == NULL) {
                $url = $this->generateUrl('app_homepage');
            } else {
                $url = $referer;
            }

            return $this->redirect($url);
        }

        return $this->render('books/update_location.html.twig', [
            'form' => $form->createView(),
            'id' => $id
        ]);
    }
}

templates/books/add.html.twig
{% extends 'base.html.twig' %}

{% form_theme form 'form/fields.html.twig' %}

{% block body %}
    <div class="ui grid centered">
        <div class="eight wide column">
            <h1>Add a new book</h1>
            {{ form(form) }}
        </div>
    </div>
{% endblock %}

templates/books/borrow_success.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="ui grid centered">
        <div class="column">
            <h1>You have borrowed the book!</h1>
            <p>Please remember about returning it and updating its status.</p>
        </div>
    </div>
{% endblock %}

templates/books/edit.html.twig
{% extends 'base.html.twig' %}

{% form_theme form 'form/fields.html.twig' %}

{% block body %}
    <div class="ui grid centered">
        <div class="eight wide column">
            <h1>Edit a book</h1>
            {{ form(form) }}
        </div>
    </div>
{% endblock %}

templates/books/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <table class="ui green table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Author</th>
                <th>Location</th>
                <th>Current reader</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
                <tr>
                    <td><a href="{{ path('app_books_show', { 'id': book.id }) }}">{{ book.title }}</a></td>
                    <td>{{ book.author }}</td>
                    <td>
                        {{ book.location }}
                        (<a href="#" data-modal-trigger="book-location:{{ book.id }}">change</a>)
                        {{ render(controller(
                            'App\\Controller\\BooksController::updateLocation',
                            { 'id': book.id }
                        )) }}
                    </td>
                    <td>
                        {% if book.isBorrowed %}
                            {{ book.currentReader.username }}
                        {% else %}
                            <a href="{{ path('app_books_borrow', { 'id': book.id }) }}" class="ui primary button">Borrow</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/books/return_success.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="ui grid centered">
        <div class="column">
            <h1>Thank you for returning the book!</h1>
        </div>
    </div>
{% endblock %}

templates/books/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="ui grid centered">
        <div class="eight wide column">
            <h1>{{ book.title }} by {{ book.author }}</h1>
            <p>
                <strong>Owner</strong><br>
                {{ book.owner }}
            </p>
            <p>
                <strong>Location</strong><br>
                {{ book.location }}
            </p>
            <p>
                <strong>Description</strong><br>
                {{ book.description }}
            </p>
            {% if book.isBorrowed %}
                <p>This book is being read by {{ book.currentReader.username }}.</p>
            {% else %}
                <a href="{{ path('app_books_borrow', { 'id': book.id }) }}" class="ui primary button">Borrow</a>
            {% endif %}
            <a href="{{ path('app_books_edit', { 'id': book.id }) }}" class="ui primary button">Edit</a>
        </div>
    </div>
{% endblock %}

templates/books/update_location.html.twig
{% form_theme form 'form/fields.html.twig' %}

<div class="ui small modal" data-modal="book-location:{{ id }}">
    <i class="close icon"></i>
    <div class="header">Change the location</div>
    <div class="content">
        {{ form(form) }}
    </div>
</div>